version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./containers/rails/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/sample_app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'

  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - '80:80'
